# Supabaseの設定
supabase_url = "https://magpiirlkjxillhmvdrh.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hZ3BpaXJsa2p4aWxsaG12ZHJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMjk2MDksImV4cCI6MjA1NzgwNTYwOX0.hKSV4dc1IkmmHz-61vcLwLCeeWW0M-vJbp6R2JXZwq8"

# アプリケーションパスワード
password = "nora1nora"